### ISSUE TITLE
关于api扫码登录的问题

### ISSUE THREAD

**Issue by tianlongbaobao** [MuoRanLY/DLUTToolBoxMobileV2#2]
2024.12.19：
目前无论是最新版i大工官方软件还是DLUTToolBoxMobileV2均已经不能在api的身份认证网址进行扫码登录
我自己在用arkts的axios将代码转换后：
PreLogin返回：
{"data":[],"ret":0,"errcode":0,"errmsg":"ok"}
<img width="405" alt="联想截图_20241219131619" src="https://github.com/user-attachments/assets/112b1bb2-5c39-49e4-a8c7-21a1492894b6" />
Login返回：
{"data":[],"ret":0,"errcode":0,"errmsg":"ok"}
<img width="407" alt="联想截图_20241219131755" src="https://github.com/user-attachments/assets/72162315-a0cc-41a7-8a3d-17beff7143f7" />

返回的结果没问题，但是网页却提示二维码已过期且无法跳转，最新版i大工官方软件和DLUTToolBoxMobileV2出现相同的情况
个人猜测这个接口的后端目前出现了问题

**Comment by IShiraiKurokoI** [comment]
哦，这个啊，这里扫码登录我记得好像是好久之前就废了，因为本身按sso的流程的话正常情况下你不应该看到这个页面，我记得是这样。sso的扫码应该是能用的吧

**Comment by tianlongbaobao** [comment]
> 哦，这个啊，这里扫码登录我记得好像是好久之前就废了，因为本身按sso的流程的话正常情况下你不应该看到这个页面，我记得是这样。sso的扫码应该是能用的吧

sso扫码登录正常，只是看到代码中有写，在用arkts转换的时候遇到了这个问题，感谢作者回复。
